# Site
title:              OleNet
bio:                'OleNet Liujiaxiang'
description:        "Olé is an interjection. an exclamation of approval or encouragement customary at bullfights, flamenco dancing, and other Spanish or Latin American events. noun."
locale:             cn
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
  input:  GFM
  extensions:
    - autolink
    - footnotes
    - smart
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            LIUJiaXiang
facebook:           default
instagram:          default
github:             OleNet
500px:              olenet

# personal
location:           Beijing
phone:              xxx-xxxx-xxxx
email:              olenet@126.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-toc

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]

