title: OleNet
email: olenet##126.com
description: >- # this means to ignore newlines until "baseurl:"
  Olé is an interjection. an exclamation of approval or encouragement customary at bullfights, flamenco dancing, and other Spanish or Latin American events. noun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


rss: rss
analytics-id:       "default"
twitter:            LIUJiaXiang
facebook:           default
instagram:          default
github:             OleNet
500px:              olenet

location:           Beijing

plugins:
 - jekyll-feed

mathjax:            true


markdown: kramdown
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: jekyll-theme-slate

